image: vlafeychine/rust

.push-zamok: &push-zamok
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -rqz ${ZAMOK_SOURCE}/. v-lafeychine@zamok.crans.org:www/proost/${ZAMOK_TARGET}

stages: [check, build, tests, docs]

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cache/cargo/"
  RUSTFLAGS: "-D warnings"

cache:
  key: "$CI_JOB_STAGE"
  paths:
    - .cache/cargo/
    - target/

default:
  interruptible: true

format:
  cache: []
  stage: check
  script:
    - cargo fmt --check

lint:
  stage: check
  script:
    - cargo clippy --all-targets --all-features

build:
  stage: build
  script:
    - cargo build

tests:
  stage: tests

  variables:
    CARGO_INCREMENTAL: 0
    EXCLUDE_BR_REGEXP: "#\\[|unreachable!|assert(_eq)?!"
    EXCLUDE_REGEXP: "//!|///|#\\[|use"
    GRCOV: "grcov . -s . -b ./target/debug/ --branch --ignore-not-existing --excl-line ${EXCLUDE_REGEXP} --excl-br-line ${EXCLUDE_BR_REGEXP}"
    RUSTDOCFLAGS: "${RUSTFLAGS}"
    RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    ZAMOK_SOURCE: coverage
    ZAMOK_TARGET: coverage/${CI_COMMIT_REF_SLUG}

  script:
    - cargo test
    - ${GRCOV} --ignore "*cargo*" -t cobertura -o ./coverage.xml || true
    - xsltproc --output ./target/coverage.xml ./.gitlab-cov.xsl ./coverage.xml
    - ${GRCOV} --ignore "*cargo*" -t lcov -o ./target/coverage.lcov || true
    - genhtml --branch --no-function-coverage --precision 2 ./target/coverage.lcov -o ./coverage
    - find ./target \( -name "*.gcda" -or -name "*.gcno" \) -delete
    - *push-zamok

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./target/coverage.xml

  coverage: '/^  branches...: \d+.\d+%/'


docs:
  stage: docs

  variables:
    ZAMOK_SOURCE: target/doc
    ZAMOK_TARGET: doc

  only:
    refs:
      - main

  script:
    - cargo doc --no-deps
    - *push-zamok
