[workspace]
members = [
    "kernel",
    "parser",
    "proost",
    "tilleul",
    "elaboration"
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.100"
bumpalo = "3.19.1"
clap = { version = "4.5.54", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["full"] }

[workspace.package]
authors = [
    "Arthur Adjedj",
    "Augustin Albert",
    "Vincent Lafeychine",
    "Lucas Tabary-Maujean"
]
edition = "2024"
version = "0.3.0"
license = "GPL-3.0-or-later"
repository = "https://gitlab.crans.org/loutr/proost"
