[workspace]
members = [
    "kernel",
    "parser",
    "proost",
]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.0.10", features = ["derive"] }
derive_more = "0.99.17"
num-bigint = "0.4"
atty = "0.2"
colored = "2"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"

[workspace.package]
authors = [
    "Arthur Adjedj",
    "Augustin Albert",
    "Lucas Tabary-Maujean",
    "Vincent Lafeychine"
]
license = "GPL-3.0-or-later"
