[package]
name = "tilleul"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "A LSP server for the simple proof assistant Proost"

[dependencies]
parser = { path = "../parser" }
kernel = { path = "../kernel" }
