[package]
name = "kernel"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
derive_more.workspace = true

bumpalo = "3.11.1"
im-rc = "15.1.0"
