[package]
name = "kernel"
edition = "2021"
version = "0.1.0"
authors.workspace = true
license.workspace = true

[dependencies]
derive_more.workspace = true
num-bigint.workspace = true

[dev-dependencies]
lazy_static = "1.4.0"
bumpalo.workspace = true
im-rc.workspace = true
