[package]
name = "parser"
edition = "2021"
version = "0.1.0"
authors.workspace = true
license.workspace = true

[dependencies]
kernel.path = "../kernel"

derive_more.workspace = true
num-bigint.workspace = true
pest.workspace = true
pest_derive.workspace = true
