[package]
name = "parser"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kernel.path = "../kernel"

derive_more.workspace = true
pest.workspace = true
pest_derive.workspace = true
