[package]
name = "parser"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
kernel.path = "../kernel"
utils.path = "../utils"

derive_more.workspace = true

pest = "2.5"
pest_derive = "2.5"
