[package]
name = "parser"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
kernel.path = "../kernel"
elaboration.path = "../elaboration"

derive_more.workspace = true

pest = "2"
pest_derive = "2"
