[package]
name = "proost"
description = "A simple proof assistant written in Rust"
edition = "2021"
version = "0.1.0"
authors.workspace = true
license.workspace = true

[dependencies]
kernel.path = "../kernel"
parser.path = "../parser"

anyhow.workspace = true
clap.workspace = true

colored = "2"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
