[package]
name = "proost"
description = "A simple proof assistant written in Rust"
edition = "2021"
version = "0.1.0"
authors.workspace = true
license.workspace = true

[dependencies]
kernel.path = "../kernel"
parser.path = "../parser"

anyhow.workspace = true
clap.workspace = true
atty.workspace = true
colored.workspace = true
rustyline.workspace = true
rustyline-derive.workspace = true
